// this is a read only file generated by manual inputs to file mustache/templates/rates/contracts.js.
export let contractsToInstances = new Map<string, string>();
contractsToInstances.set("0x84443cfd09a48af6ef360c6976c5392ac5023a1f", // Instance-bnb-0.1
  "bnb-0.1"
);
contractsToInstances.set("0xd47438c816c9e7f2e2888e060936a499af9582b3", // Instance-bnb-1
  "bnb-1"
);
contractsToInstances.set("0x330bdfade01ee9bf63c209ee33102dd334618e0a", // Instance-bnb-10
  "bnb-10"
);
contractsToInstances.set("0x1e34a77868e19a6647b1f2f47b51ed72dede95dd", // Instance-bnb-100
  "bnb-100"
);
contractsToInstances.set("0x1e34a77868e19a6647b1f2f47b51ed72dede95dd", // Instance-xdai-100
  "xdai-100"
);
contractsToInstances.set("0xdf231d99ff8b6c6cbf4e9b9a945cbacef9339178", // Instance-xdai-1000
  "xdai-1000"
);
contractsToInstances.set("0xaf4c0b70b2ea9fb7487c7cbb37ada259579fe040", // Instance-xdai-10000
  "xdai-10000"
);
contractsToInstances.set("0xa5c2254e4253490c54cef0a4347fddb8f75a4998", // Instance-xdai-100000
  "xdai-100000"
);
contractsToInstances.set("0x1e34a77868e19a6647b1f2f47b51ed72dede95dd", // Instance-matic-100
  "matic-100"
);
contractsToInstances.set("0xdf231d99ff8b6c6cbf4e9b9a945cbacef9339178", // Instance-matic-1000
  "matic-1000"
);
contractsToInstances.set("0xaf4c0b70b2ea9fb7487c7cbb37ada259579fe040", // Instance-matic-10000
  "matic-10000"
);
contractsToInstances.set("0xa5c2254e4253490c54cef0a4347fddb8f75a4998", // Instance-matic-100000
  "matic-100000"
);
contractsToInstances.set("0x4e75240082787d802d226ca4206bfef1b842b730", // Instance-eth-0.1
  "eth-0.1"
);
contractsToInstances.set("0x45e0f782c003163c1ce447b983852713ae946510", // Instance-eth-1
  "eth-1"
);
contractsToInstances.set("0xa9393f2311ac8833490cbacc5f04ca139a8f6f95", // Instance-eth-10
  "eth-10"
);
contractsToInstances.set("0xa1db19284b51db09a921c8d24e1f20e57c8d1462", // Instance-eth-100
  "eth-100"
);
contractsToInstances.set("0xd4b88df4d29f5cedd6857912842cff3b20c8cfa3", // Instance-dai-100
  "dai-100"
);
contractsToInstances.set("0xfd8610d20aa15b7b2e3be39b396a1bc3516c7144", // Instance-dai-1000
  "dai-1000"
);
contractsToInstances.set("0x07687e702b410fa43f4cb4af7fa097918ffd2730", // Instance-dai-10000
  "dai-10000"
);
contractsToInstances.set("0x23773e65ed146a459791799d01336db287f25334", // Instance-dai-100000
  "dai-100000"
);
contractsToInstances.set("0x22aaa7720ddd5388a3c0a3333430953c68f1849b", // Instance-cdai-5000
  "cdai-5000"
);
contractsToInstances.set("0x03893a7c7463ae47d46bc7f091665f1893656003", // Instance-cdai-50000
  "cdai-50000"
);
contractsToInstances.set("0x2717c5e28cf931547b621a5dddb772ab6a35b701", // Instance-cdai-500000
  "cdai-500000"
);
contractsToInstances.set("0xd21be7248e0197ee08e0c20d4a96debdac3d20af", // Instance-cdai-5000000
  "cdai-5000000"
);
contractsToInstances.set("0xd96f2b1c14db8458374d9aca76e26c3d18364307", // Instance-usdc-100
  "usdc-100"
);
contractsToInstances.set("0x4736dcf1b7a3d580672cce6e7c65cd5cc9cfba9d", // Instance-usdc-1000
  "usdc-1000"
);
contractsToInstances.set("0xdc5aab9c200fcc435eb07d8a7719bdc62c91865c", // Instance-usdt-100
  "usdt-100"
);
contractsToInstances.set("0xc773c7ce4b8e12d4e6970ec926562dcbe7f341c9", // Instance-usdt-1000
  "usdt-1000"
);
contractsToInstances.set("0x08f0889e5d31a8f9cac80be9f823771c3203217f", // Instance-usdt-10000
  "usdt-10000"
);
contractsToInstances.set("0xa7063672d2a8680692887b4416fb11df19588961", // Instance-usdt-100000
  "usdt-100000"
);
contractsToInstances.set("0x178169b423a011fff22b9e3f3abea13414ddd0f1", // Instance-wbtc-0.1
  "wbtc-0.1"
);
contractsToInstances.set("0x610b717796ad172b316836ac95a2ffad065ceab4", // Instance-wbtc-1
  "wbtc-1"
);
contractsToInstances.set("0xbb93e510bbcd0b7beb5a853875f9ec60275cf498", // Instance-wbtc-10
  "wbtc-10"
);
contractsToInstances.set("0x1b98e8cfa0c451bf03e1d4700ff593f234d786da", // Instance-usdt-100
  "usdt-100"
);
contractsToInstances.set("0x591eb6a2f04138da4216747adeccb3f7119397b1", // Instance-eth-0.1
  "eth-0.1"
);
contractsToInstances.set("0x330bdfade01ee9bf63c209ee33102dd334618e0a", // Instance-avax-10
  "avax-10"
);
contractsToInstances.set("0x1e34a77868e19a6647b1f2f47b51ed72dede95dd", // Instance-avax-100
  "avax-100"
);
contractsToInstances.set("0xaf8d1839c3c67cf571aa74b5c12398d4901147b3", // Instance-avax-500
  "avax-500"
);
contractsToInstances.set("0x84443cfd09a48af6ef360c6976c5392ac5023a1f", // Instance-eth-0.1
  "eth-0.1"
);
contractsToInstances.set("0xd47438c816c9e7f2e2888e060936a499af9582b3", // Instance-eth-1
  "eth-1"
);
contractsToInstances.set("0x330bdfade01ee9bf63c209ee33102dd334618e0a", // Instance-eth-10
  "eth-10"
);
contractsToInstances.set("0x1e34a77868e19a6647b1f2f47b51ed72dede95dd", // Instance-eth-100
  "eth-100"
);
contractsToInstances.set("0x84443cfd09a48af6ef360c6976c5392ac5023a1f", // Instance-eth-0.1
  "eth-0.1"
);
contractsToInstances.set("0xd47438c816c9e7f2e2888e060936a499af9582b3", // Instance-eth-1
  "eth-1"
);
contractsToInstances.set("0x330bdfade01ee9bf63c209ee33102dd334618e0a", // Instance-eth-10
  "eth-10"
);
contractsToInstances.set("0x1e34a77868e19a6647b1f2f47b51ed72dede95dd", // Instance-eth-100
  "eth-100"
);
// this is a read only file generated by manual inputs to file mustache/templates/rates/contracts.js.
